# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/tmp/NTOS/oldflight

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/tmp/NTOS/oldflight

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/tmp/NTOS/oldflight/CMakeFiles /Volumes/tmp/NTOS/oldflight//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/tmp/NTOS/oldflight/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flight

# Build rule for target.
flight: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flight
.PHONY : flight

# fast build rule for target.
flight/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/build
.PHONY : flight/fast

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named dmg

# Build rule for target.
dmg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dmg
.PHONY : dmg

# fast build rule for target.
dmg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmg.dir/build.make CMakeFiles/dmg.dir/build
.PHONY : dmg/fast

b747.o: b747.c.o
.PHONY : b747.o

# target to build an object file
b747.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/b747.c.o
.PHONY : b747.c.o

b747.i: b747.c.i
.PHONY : b747.i

# target to preprocess a source file
b747.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/b747.c.i
.PHONY : b747.c.i

b747.s: b747.c.s
.PHONY : b747.s

# target to generate assembly for a file
b747.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/b747.c.s
.PHONY : b747.c.s

c150.o: c150.c.o
.PHONY : c150.o

# target to build an object file
c150.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/c150.c.o
.PHONY : c150.c.o

c150.i: c150.c.i
.PHONY : c150.i

# target to preprocess a source file
c150.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/c150.c.i
.PHONY : c150.c.i

c150.s: c150.c.s
.PHONY : c150.s

# target to generate assembly for a file
c150.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/c150.c.s
.PHONY : c150.c.s

color.o: color.c.o
.PHONY : color.o

# target to build an object file
color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/color.c.o
.PHONY : color.c.o

color.i: color.c.i
.PHONY : color.i

# target to preprocess a source file
color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/color.c.i
.PHONY : color.c.i

color.s: color.c.s
.PHONY : color.s

# target to generate assembly for a file
color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/color.c.s
.PHONY : color.c.s

demo.o: demo.c.o
.PHONY : demo.o

# target to build an object file
demo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/demo.c.o
.PHONY : demo.c.o

demo.i: demo.c.i
.PHONY : demo.i

# target to preprocess a source file
demo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/demo.c.i
.PHONY : demo.c.i

demo.s: demo.c.s
.PHONY : demo.s

# target to generate assembly for a file
demo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/demo.c.s
.PHONY : demo.c.s

draw_logo.o: draw_logo.c.o
.PHONY : draw_logo.o

# target to build an object file
draw_logo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/draw_logo.c.o
.PHONY : draw_logo.c.o

draw_logo.i: draw_logo.c.i
.PHONY : draw_logo.i

# target to preprocess a source file
draw_logo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/draw_logo.c.i
.PHONY : draw_logo.c.i

draw_logo.s: draw_logo.c.s
.PHONY : draw_logo.s

# target to generate assembly for a file
draw_logo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/draw_logo.c.s
.PHONY : draw_logo.c.s

f15.o: f15.c.o
.PHONY : f15.o

# target to build an object file
f15.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f15.c.o
.PHONY : f15.c.o

f15.i: f15.c.i
.PHONY : f15.i

# target to preprocess a source file
f15.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f15.c.i
.PHONY : f15.c.i

f15.s: f15.c.s
.PHONY : f15.s

# target to generate assembly for a file
f15.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f15.c.s
.PHONY : f15.c.s

f16.o: f16.c.o
.PHONY : f16.o

# target to build an object file
f16.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f16.c.o
.PHONY : f16.c.o

f16.i: f16.c.i
.PHONY : f16.i

# target to preprocess a source file
f16.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f16.c.i
.PHONY : f16.c.i

f16.s: f16.c.s
.PHONY : f16.s

# target to generate assembly for a file
f16.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f16.c.s
.PHONY : f16.c.s

f16w.o: f16w.c.o
.PHONY : f16w.o

# target to build an object file
f16w.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f16w.c.o
.PHONY : f16w.c.o

f16w.i: f16w.c.i
.PHONY : f16w.i

# target to preprocess a source file
f16w.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f16w.c.i
.PHONY : f16w.c.i

f16w.s: f16w.c.s
.PHONY : f16w.s

# target to generate assembly for a file
f16w.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f16w.c.s
.PHONY : f16w.c.s

f18.o: f18.c.o
.PHONY : f18.o

# target to build an object file
f18.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f18.c.o
.PHONY : f18.c.o

f18.i: f18.c.i
.PHONY : f18.i

# target to preprocess a source file
f18.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f18.c.i
.PHONY : f18.c.i

f18.s: f18.c.s
.PHONY : f18.s

# target to generate assembly for a file
f18.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/f18.c.s
.PHONY : f18.c.s

flight.o: flight.c.o
.PHONY : flight.o

# target to build an object file
flight.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/flight.c.o
.PHONY : flight.c.o

flight.i: flight.c.i
.PHONY : flight.i

# target to preprocess a source file
flight.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/flight.c.i
.PHONY : flight.c.i

flight.s: flight.c.s
.PHONY : flight.s

# target to generate assembly for a file
flight.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/flight.c.s
.PHONY : flight.c.s

graph.o: graph.c.o
.PHONY : graph.o

# target to build an object file
graph.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/graph.c.o
.PHONY : graph.c.o

graph.i: graph.c.i
.PHONY : graph.i

# target to preprocess a source file
graph.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/graph.c.i
.PHONY : graph.c.i

graph.s: graph.c.s
.PHONY : graph.s

# target to generate assembly for a file
graph.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/graph.c.s
.PHONY : graph.c.s

irisgl.o: irisgl.c.o
.PHONY : irisgl.o

# target to build an object file
irisgl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/irisgl.c.o
.PHONY : irisgl.c.o

irisgl.i: irisgl.c.i
.PHONY : irisgl.i

# target to preprocess a source file
irisgl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/irisgl.c.i
.PHONY : irisgl.c.i

irisgl.s: irisgl.c.s
.PHONY : irisgl.s

# target to generate assembly for a file
irisgl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/irisgl.c.s
.PHONY : irisgl.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/main.c.s
.PHONY : main.c.s

maths.o: maths.c.o
.PHONY : maths.o

# target to build an object file
maths.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/maths.c.o
.PHONY : maths.c.o

maths.i: maths.c.i
.PHONY : maths.i

# target to preprocess a source file
maths.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/maths.c.i
.PHONY : maths.c.i

maths.s: maths.c.s
.PHONY : maths.s

# target to generate assembly for a file
maths.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/maths.c.s
.PHONY : maths.c.s

meters.o: meters.c.o
.PHONY : meters.o

# target to build an object file
meters.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/meters.c.o
.PHONY : meters.c.o

meters.i: meters.c.i
.PHONY : meters.i

# target to preprocess a source file
meters.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/meters.c.i
.PHONY : meters.c.i

meters.s: meters.c.s
.PHONY : meters.s

# target to generate assembly for a file
meters.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/meters.c.s
.PHONY : meters.c.s

object.o: object.c.o
.PHONY : object.o

# target to build an object file
object.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/object.c.o
.PHONY : object.c.o

object.i: object.c.i
.PHONY : object.i

# target to preprocess a source file
object.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/object.c.i
.PHONY : object.c.i

object.s: object.c.s
.PHONY : object.s

# target to generate assembly for a file
object.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/object.c.s
.PHONY : object.c.s

p38.o: p38.c.o
.PHONY : p38.o

# target to build an object file
p38.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/p38.c.o
.PHONY : p38.c.o

p38.i: p38.c.i
.PHONY : p38.i

# target to preprocess a source file
p38.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/p38.c.i
.PHONY : p38.c.i

p38.s: p38.c.s
.PHONY : p38.s

# target to generate assembly for a file
p38.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/p38.c.s
.PHONY : p38.c.s

p38w.o: p38w.c.o
.PHONY : p38w.o

# target to build an object file
p38w.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/p38w.c.o
.PHONY : p38w.c.o

p38w.i: p38w.c.i
.PHONY : p38w.i

# target to preprocess a source file
p38w.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/p38w.c.i
.PHONY : p38w.c.i

p38w.s: p38w.c.s
.PHONY : p38w.s

# target to generate assembly for a file
p38w.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/p38w.c.s
.PHONY : p38w.c.s

uflight.o: uflight.c.o
.PHONY : uflight.o

# target to build an object file
uflight.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/uflight.c.o
.PHONY : uflight.c.o

uflight.i: uflight.c.i
.PHONY : uflight.i

# target to preprocess a source file
uflight.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/uflight.c.i
.PHONY : uflight.c.i

uflight.s: uflight.c.s
.PHONY : uflight.s

# target to generate assembly for a file
uflight.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flight.dir/build.make CMakeFiles/flight.dir/uflight.c.s
.PHONY : uflight.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... app"
	@echo "... dmg"
	@echo "... flight"
	@echo "... b747.o"
	@echo "... b747.i"
	@echo "... b747.s"
	@echo "... c150.o"
	@echo "... c150.i"
	@echo "... c150.s"
	@echo "... color.o"
	@echo "... color.i"
	@echo "... color.s"
	@echo "... demo.o"
	@echo "... demo.i"
	@echo "... demo.s"
	@echo "... draw_logo.o"
	@echo "... draw_logo.i"
	@echo "... draw_logo.s"
	@echo "... f15.o"
	@echo "... f15.i"
	@echo "... f15.s"
	@echo "... f16.o"
	@echo "... f16.i"
	@echo "... f16.s"
	@echo "... f16w.o"
	@echo "... f16w.i"
	@echo "... f16w.s"
	@echo "... f18.o"
	@echo "... f18.i"
	@echo "... f18.s"
	@echo "... flight.o"
	@echo "... flight.i"
	@echo "... flight.s"
	@echo "... graph.o"
	@echo "... graph.i"
	@echo "... graph.s"
	@echo "... irisgl.o"
	@echo "... irisgl.i"
	@echo "... irisgl.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... maths.o"
	@echo "... maths.i"
	@echo "... maths.s"
	@echo "... meters.o"
	@echo "... meters.i"
	@echo "... meters.s"
	@echo "... object.o"
	@echo "... object.i"
	@echo "... object.s"
	@echo "... p38.o"
	@echo "... p38.i"
	@echo "... p38.s"
	@echo "... p38w.o"
	@echo "... p38w.i"
	@echo "... p38w.s"
	@echo "... uflight.o"
	@echo "... uflight.i"
	@echo "... uflight.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

